version: "3.3"

services:
  db:
    image: mysql:5.7
    restart: always
    env_file:
      - ./.env.db
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3340:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    networks:
      - app
    volumes:
      - my-db:/var/lib/mysql

  app:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/frontend
    # command: sh -c "npm run dev"
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    networks:
      - app

  api:
    image: zaker237/text-similarity-server
    networks:
      - app
    ports:
    - "8002:8002"

networks:
  app:
    driver: bridge

# Names our volume
volumes:
  my-db: